# cloudbuild.yaml
steps:
  # Setup build directory
  - name: 'ubuntu'
    args:
      - 'bash'
      - '-c'
      - |
        mkdir -p /workspace/build/prisma && \
        cp -r /workspace/apps/web/prisma/* /workspace/build/prisma/ && \
        cp -r /workspace/packages/speech-service/* /workspace/build/ && \
        echo "Build directory contents:" && \
        ls -R /workspace/build

  # Debug: Check build directory
  - name: 'ubuntu'
    args: ['bash', '-c', 'echo "Final build directory:" && ls -la /workspace/build']

  # Build the container
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '--no-cache'
      - '--progress=plain'
      - '-t'
      - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/gcr-repo/speech-service'
      - '/workspace/build'

images:
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/gcr-repo/speech-service'

options:
  logging: CLOUD_LOGGING_ONLY
  dynamicSubstitutions: true